#pragma once

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logApp)
Q_DECLARE_LOGGING_CATEGORY(logMpv)
Q_DECLARE_LOGGING_CATEGORY(logFfprobe)
Q_DECLARE_LOGGING_CATEGORY(logExport)
Q_DECLARE_LOGGING_CATEGORY(logUi)
